## Trigonometric Functions

NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

Example

Find sine value of PI/2:

In [1]:
import numpy as np

x = np.sin(np.pi/2)

print(x)

1.0


Example

Find sine values for all of the values in arr:

In [2]:
import numpy as np

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


## Convert Degrees Into Radians

By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumP.

Note: radians values are pi/180 * degree_values.

In [3]:
import numpy as np

arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


## Radians to Degrees

Example

Convert all of the values in following array arr to degrees:

In [4]:
import numpy as np

arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


## Finding Angles

Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

Example

Find the angle of 1.0:

In [5]:
import numpy as np

x = np.arcsin(1.0)

print(x)

1.5707963267948966


## Angles of Each Value in Arrays

Example

Find the angle for all of the sine values in the array

In [6]:
import numpy as np

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


## Hypotenues

Finding hypotenues using pythagoras theorem in NumPy.

NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

Example

Find the hypotenues for 4 base and 3 perpendicular:

In [7]:
import numpy as np

base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0
